logging:
  level:
    org.springframework: DEBUG

server:
  port: 4050

sms:
  dingtalk:
    webhook: https://oapi.dingtalk.com/robot/send?access_token=8d9ef9c9e2b9be2b1c6d5406a8f12664e6511ff37d9158230beb6ac982dbf7a8
  aliyun:
    accessKey: LTAInWSoFHGTF2oU
    secretKey: oSNbFnYaatQvPZtu0G20wtUZnYSy9M
    channels:
      loginCodeChannel: SMS_6705685
      serviceStatusChange: SMS_6705680

spring:
  rabbitmq:
    host: 192.168.1.213
    port: 5672
    username: admin
    password: admin