logging:
  level:
    org.springframework: DEBUG

server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.213:3306/vole?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 192.168.1.213:2181
      namespace: vole-job
