server:
  port: 8600

spring:
  application:
    name: vole-turbine

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://vole-eureka-node1:1026/eureka/,http://vole-eureka-node2:1027/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


turbine:
  app-config: vole-mps,vole-demo,vole-passport,vole-auth,vole-gateway,vole-portal,vole-portal-data
  aggregator:
    # turbine聚集数据的粒度
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host-port: true
